# Generated by Django 3.1.5 on 2021-01-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='primaria_o_secundaria',
            field=models.CharField(max_length=128),
        ),
    ]
