# Generated by Django 3.1.5 on 2021-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210125_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='estatus_de_inscripcion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='primaria_o_secundaria',
            field=models.BooleanField(default=False),
        ),
    ]
