# Generated by Django 3.1.5 on 2021-01-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210125_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='primaria_o_secundaria',
            new_name='secundaria',
        ),
    ]
